### ISSUE TITLE
 Class constructor [ComponentName] cannot be invoked without 'new'.

### ISSUE THREAD

**Issue by hally9k** [Oblosys/react-lifecycle-visualizer#4]
I am getting this error when adding traceLifecycle to a component in this repro:

https://github.com/hally9k/react-render-cascade

I am trying to repro some cascading render issues.

Stacktrace:
```
Error: Class constructor Iterative cannot be invoked without 'new'
    at new TracingComponent (http://localhost:9090/app.js:21884:124)
    at constructClassInstance (http://localhost:9090/app.js:10974:20)
    at updateClassComponent (http://localhost:9090/app.js:12509:9)
    at beginWork (http://localhost:9090/app.js:13155:16)
    at performUnitOfWork (http://localhost:9090/app.js:15987:16)
    at workLoop (http://localhost:9090/app.js:16016:26)
    at HTMLUnknownElement.callCallback (http://localhost:9090/app.js:4273:14)
    at Object.invokeGuardedCallbackDev (http://localhost:9090/app.js:4311:16)
    at invokeGuardedCallback (http://localhost:9090/app.js:4360:29)
    at replayUnitOfWork (http://localhost:9090/app.js:15491:7)
```

**Comment by Oblosys** [comment]
Interesting. This happens because `react-render-cascade` doesn't transpile classes, and `react-lifecycle-visualizer` does, and transpiled classes cannot extend native es6 classes (see for example babel/babel/issues/7221). There seems to be a PR (babel/babel/pull/7081), but it isn't showing much activity.

The easiest way to get around it is to transpile es6 classes in your project by using [babel-preset-env](https://www.npmjs.com/package/babel-preset-env), or by adding `'transform-es2015-modules-commonjs'` to the `plugins` in your `.babelrc`.
